db:
  dsn: root:%s@tcp(test.abc.red:3306)/ha666db?charset=utf8&parseTime=true&loc=Asia%%2fShanghai
  db_name: ha666db
  maxidle_conn: 5
  maxopen_conn: 100
  pwd: "1234567890"
app:
  jwt:
    secret: G8IFWoOd!m9N8RCNUn?%WeH-f_3HNGQl
port: 9090
